Algoritmo "olá, mundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guanabara 
// Descrição   : Imprime no console a frase "Olá, mundo!"
// Autor(a)    : Samuel Tank
// Data atual  : 8/21/2021
Var
// Seção de Declarações das variáveis 
msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

msg <- "Olá, mundo!"

escreval("Mensagem: ", msg) //No visualg, não há operador de concatenação, para isso, use a (,)


Fimalgoritmo