Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guanabara 
// Descrição   :
// Autor(a)    : Samuel Tank
// Data atual  : 8/21/2021
Var
// Seção de Declarações das variáveis 

name: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Digite seu nome: ")
leia(name)

escreva("*** Seja Bem-vindo ", name, "! ***")

Fimalgoritmo