Algoritmo "Combinações"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Guanabara 
// Descrição   : Exibe um sequência de títulos e subtítulos.
// Autor(a)    : Samuel de Tank
// Data atual  : 9/7/2021
Var

   contador, contador1: inteiro

Inicio

   para contador <- 1 ate 10 faca
      para contador1 <- 1 até 10 faca
         escreval(contador," -",contador1)
      fimpara
   fimpara

Fimalgoritmo