Algoritmo "vetor - dissecando matrizes"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Guanabara 
// Descrição   : Recebe valores para uma matriz de quarta ordem;
// Autor(a)    : Samuel Tank
// Data atual  : 9/18/2021
Var

   matrizPrincipal: vetor[1..4,1 ..4]
   i, j:inteiro

Inicio

   para i <- 1 ate 4 faca
      para j <- 1 ate 4 faca
         escreva("Digite um valor para o índice [",i,",",j"]: ")
         leia()
      fimpara
   fimpara

Fimalgoritmo